//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public string cMcData { get; set; }
        public string cAttendanceCode { get; set; }
        public string cFlag { get; set; }
        public Nullable<int> nTmmn { get; set; }
        public string cTmhh { get; set; }
        public string cMcNo { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public string IPAddress { get; set; }
    }
}
