//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class holidayback
    {
        public int Id { get; set; }
        public string cHolidayCode { get; set; }
        public string cHolidayDesc { get; set; }
        public System.DateTime dtDate { get; set; }
        public string cStatusCode { get; set; }
        public string cLocationCode { get; set; }
        public string cBUCode { get; set; }
    }
}
