//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalanceTable
    {
        public int Id { get; set; }
        public string cEmployeeCode { get; set; }
        public string cCardNumber { get; set; }
        public string cEmployeeName { get; set; }
        public Nullable<System.DateTime> cYear { get; set; }
        public Nullable<decimal> PL_OpeningBalance { get; set; }
        public Nullable<decimal> PL_Credit { get; set; }
        public Nullable<decimal> AL_Credit { get; set; }
        public Nullable<decimal> AL_OpeningBalance { get; set; }
        public Nullable<decimal> BT_Credit { get; set; }
        public Nullable<decimal> PAT_Credit { get; set; }
    }
}
