//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leavebalanceback
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> cYear { get; set; }
        public string cCardNumber { get; set; }
        public Nullable<decimal> PL_OP { get; set; }
        public Nullable<decimal> PL_CR { get; set; }
        public Nullable<decimal> AL_CR { get; set; }
        public Nullable<decimal> AL_OP { get; set; }
    }
}
