//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMastertemp
    {
        public string cPrimary { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public string cCardNumber { get; set; }
        public string cShiftCode { get; set; }
        public string cStatus { get; set; }
    }
}
