//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIp
    {
        public string IPAdd { get; set; }
        public string Mac1 { get; set; }
        public string Mac2 { get; set; }
        public string Path { get; set; }
        public string McName { get; set; }
        public string cLocationcode { get; set; }
    }
}
