//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempsch
    {
        public string cPrimary { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public string cCardNumber { get; set; }
        public string cShiftCode { get; set; }
        public string cStatus { get; set; }
        public string cTimeIn { get; set; }
        public Nullable<int> nTimeIn { get; set; }
        public string cTimeOut { get; set; }
        public Nullable<int> nTimeOut { get; set; }
        public string cLunchFrom { get; set; }
        public Nullable<int> nLunchFrom { get; set; }
        public string cLunchTo { get; set; }
        public Nullable<int> nLunchTo { get; set; }
        public string cLate { get; set; }
        public Nullable<int> nLate { get; set; }
        public string cEarly { get; set; }
        public Nullable<int> nEarly { get; set; }
        public string cOverTime { get; set; }
        public Nullable<int> nOverTime { get; set; }
        public string cTotalHrs { get; set; }
        public Nullable<int> nTotalHrs { get; set; }
        public string cLateAuth { get; set; }
        public string cEarlyAuth { get; set; }
        public string cOverTimeAuth { get; set; }
    }
}
