//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class templv
    {
        public int Id { get; set; }
        public string cLeavetypecode { get; set; }
        public string cCarry { get; set; }
        public string cCredit { get; set; }
    }
}
